# Generated by Django 5.2.4 on 2025-09-13 18:44

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('bibliotheque', '0001_initial'),
        ('comptes', '0005_remove_rendezvous_livre_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='livre',
            name='auteur',
        ),
        migrations.RemoveField(
            model_name='livre',
            name='categorie',
        ),
        migrations.DeleteModel(
            name='Auteur',
        ),
        migrations.DeleteModel(
            name='Categorie',
        ),
        migrations.DeleteModel(
            name='Livre',
        ),
    ]
