# Generated by Django 5.1.5 on 2025-09-03 13:39

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('bibliotheque', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Utilisateur',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('email', models.EmailField(max_length=254, unique=True)),
                ('mot_de_passe', models.CharField(max_length=128)),
                ('nom', models.CharField(max_length=100)),
                ('prenom', models.CharField(max_length=100)),
                ('type_utilisateur', models.CharField(choices=[('etudiant', 'Étudiant'), ('professionnel', 'Professionnel'), ('membre_entreprise', "Membre d'entreprise")], max_length=20)),
                ('profession', models.CharField(blank=True, max_length=100, null=True)),
                ('institution', models.CharField(blank=True, max_length=100, null=True)),
                ('secteur_activite', models.CharField(blank=True, max_length=100, null=True)),
                ('adresse', models.TextField(blank=True, null=True)),
                ('telephone', models.CharField(blank=True, max_length=20, null=True)),
                ('photo', models.ImageField(blank=True, null=True, upload_to='photos_usagers/')),
                ('date_inscription', models.DateTimeField(auto_now_add=True)),
                ('derniere_connexion', models.DateTimeField(blank=True, null=True)),
                ('est_actif', models.BooleanField(default=True)),
                ('est_admin', models.BooleanField(default=False)),
                ('est_bibliothecaire', models.BooleanField(default=False)),
                ('est_personnel', models.BooleanField(default=False)),
                ('favoris', models.ManyToManyField(blank=True, related_name='favoris_utilisateurs', to='bibliotheque.livre')),
            ],
        ),
        migrations.CreateModel(
            name='RendezVous',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('statut', models.CharField(choices=[('en_attente', 'En attente'), ('confirme', 'Confirmé'), ('annule', 'Annulé'), ('termine', 'Terminé')], default='en_attente', max_length=20)),
                ('nom', models.CharField(max_length=100)),
                ('prenom', models.CharField(max_length=100)),
                ('telephone', models.CharField(max_length=20)),
                ('email', models.EmailField(max_length=254)),
                ('type_utilisateur', models.CharField(choices=[('etudiant_chercheur', 'Étudiant Chercheur'), ('professeur_chercheur', 'Professeur Chercheur'), ('academique', 'Académique'), ('professionnel', 'Professionnel'), ('porteur_projet', 'Porteur de projet'), ('autre', 'Autre')], max_length=50)),
                ('titre_ouvrage', models.CharField(blank=True, max_length=200, null=True)),
                ('auteur_ouvrage', models.CharField(blank=True, max_length=200, null=True)),
                ('numero_inventaire', models.CharField(blank=True, max_length=100, null=True)),
                ('ancien_code', models.CharField(blank=True, max_length=100, null=True)),
                ('raison', models.TextField()),
                ('date_souhaitee', models.DateField()),
                ('message', models.TextField(blank=True, null=True)),
                ('date_creation', models.DateTimeField(auto_now_add=True)),
                ('heure_entree', models.TimeField(blank=True, null=True)),
                ('heure_sortie', models.TimeField(blank=True, null=True)),
                ('livre', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='rendezvous', to='bibliotheque.livre')),
                ('utilisateur', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='comptes.utilisateur')),
            ],
        ),
        migrations.CreateModel(
            name='Notification',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('message', models.TextField()),
                ('url', models.CharField(blank=True, max_length=255, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('lu', models.BooleanField(default=False)),
                ('utilisateur', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='notifications', to='comptes.utilisateur')),
            ],
            options={
                'ordering': ['-created_at'],
            },
        ),
    ]
