# Generated by Django 5.2.4 on 2025-08-03 17:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('auth', '0012_alter_user_first_name_max_length'),
        ('comptes', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='profilbibliotheque',
            name='date_inscription',
        ),
        migrations.RemoveField(
            model_name='profilbibliotheque',
            name='numero_carte',
        ),
        migrations.AddField(
            model_name='profilbibliotheque',
            name='photo',
            field=models.ImageField(blank=True, null=True, upload_to='photos_usagers/'),
        ),
        migrations.AddField(
            model_name='profilbibliotheque',
            name='secteur_activite',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
        migrations.AddField(
            model_name='profilbibliotheque',
            name='telephone',
            field=models.CharField(blank=True, max_length=20, null=True),
        ),
        migrations.AddField(
            model_name='profilbibliotheque',
            name='type_utilisateur',
            field=models.CharField(choices=[('etudiant', 'Étudiant'), ('professionnel', 'Professionnel'), ('membre_entreprise', "Membre d'entreprise")], default='professionnel', max_length=20),
        ),
        migrations.AlterField(
            model_name='profilbibliotheque',
            name='adresse',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='profilbibliotheque',
            name='profession',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
        migrations.AlterField(
            model_name='usager',
            name='groups',
            field=models.ManyToManyField(blank=True, help_text='Les groupes auxquels cet utilisateur appartient.', related_name='usager_set', related_query_name='usager', to='auth.group', verbose_name='groupes'),
        ),
        migrations.AlterField(
            model_name='usager',
            name='user_permissions',
            field=models.ManyToManyField(blank=True, help_text='Permissions spécifiques pour cet utilisateur.', related_name='usager_set', related_query_name='usager', to='auth.permission', verbose_name='permissions utilisateur'),
        ),
    ]
