# Generated by Django 5.1.5 on 2025-09-03 13:41

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('comptes', '0001_initial'),
    ]

    operations = [
    ]
