# Generated by Django 5.1.5 on 2025-09-03 13:54

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('bibliotheque', '0001_initial'),
        ('comptes', '0002_auto_20250903_1441'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='notification',
            options={'ordering': ['-created_at'], 'verbose_name': 'Notification', 'verbose_name_plural': 'Notifications'},
        ),
        migrations.AlterModelOptions(
            name='rendezvous',
            options={'ordering': ['-date_creation'], 'verbose_name': 'Rendez-vous', 'verbose_name_plural': 'Rendez-vous'},
        ),
        migrations.AlterModelOptions(
            name='utilisateur',
            options={'ordering': ['-date_inscription'], 'verbose_name': 'Utilisateur', 'verbose_name_plural': 'Utilisateurs'},
        ),
        migrations.AlterField(
            model_name='notification',
            name='created_at',
            field=models.DateTimeField(auto_now_add=True, verbose_name='Date de création'),
        ),
        migrations.AlterField(
            model_name='notification',
            name='lu',
            field=models.BooleanField(default=False, verbose_name='Lu'),
        ),
        migrations.AlterField(
            model_name='notification',
            name='message',
            field=models.TextField(verbose_name='Message'),
        ),
        migrations.AlterField(
            model_name='notification',
            name='url',
            field=models.CharField(blank=True, max_length=255, null=True, verbose_name='URL'),
        ),
        migrations.AlterField(
            model_name='notification',
            name='utilisateur',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='notifications', to='comptes.utilisateur', verbose_name='Utilisateur'),
        ),
        migrations.AlterField(
            model_name='rendezvous',
            name='ancien_code',
            field=models.CharField(blank=True, max_length=100, null=True, verbose_name='Ancien code'),
        ),
        migrations.AlterField(
            model_name='rendezvous',
            name='auteur_ouvrage',
            field=models.CharField(blank=True, max_length=200, null=True, verbose_name="Auteur de l'ouvrage"),
        ),
        migrations.AlterField(
            model_name='rendezvous',
            name='date_creation',
            field=models.DateTimeField(auto_now_add=True, verbose_name='Date de création'),
        ),
        migrations.AlterField(
            model_name='rendezvous',
            name='date_souhaitee',
            field=models.DateField(verbose_name='Date souhaitée'),
        ),
        migrations.AlterField(
            model_name='rendezvous',
            name='email',
            field=models.EmailField(max_length=254, verbose_name='Email'),
        ),
        migrations.AlterField(
            model_name='rendezvous',
            name='heure_entree',
            field=models.TimeField(blank=True, null=True, verbose_name="Heure d'entrée"),
        ),
        migrations.AlterField(
            model_name='rendezvous',
            name='heure_sortie',
            field=models.TimeField(blank=True, null=True, verbose_name='Heure de sortie'),
        ),
        migrations.AlterField(
            model_name='rendezvous',
            name='livre',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='rendezvous', to='bibliotheque.livre', verbose_name='Livre'),
        ),
        migrations.AlterField(
            model_name='rendezvous',
            name='message',
            field=models.TextField(blank=True, null=True, verbose_name='Message'),
        ),
        migrations.AlterField(
            model_name='rendezvous',
            name='nom',
            field=models.CharField(max_length=100, verbose_name='Nom'),
        ),
        migrations.AlterField(
            model_name='rendezvous',
            name='numero_inventaire',
            field=models.CharField(blank=True, max_length=100, null=True, verbose_name="Numéro d'inventaire"),
        ),
        migrations.AlterField(
            model_name='rendezvous',
            name='prenom',
            field=models.CharField(max_length=100, verbose_name='Prénom'),
        ),
        migrations.AlterField(
            model_name='rendezvous',
            name='raison',
            field=models.TextField(verbose_name='Raison de la demande'),
        ),
        migrations.AlterField(
            model_name='rendezvous',
            name='statut',
            field=models.CharField(choices=[('en_attente', 'En attente'), ('confirme', 'Confirmé'), ('annule', 'Annulé'), ('termine', 'Terminé')], default='en_attente', max_length=20, verbose_name='Statut'),
        ),
        migrations.AlterField(
            model_name='rendezvous',
            name='telephone',
            field=models.CharField(max_length=20, verbose_name='Téléphone'),
        ),
        migrations.AlterField(
            model_name='rendezvous',
            name='titre_ouvrage',
            field=models.CharField(blank=True, max_length=200, null=True, verbose_name="Titre de l'ouvrage"),
        ),
        migrations.AlterField(
            model_name='rendezvous',
            name='type_utilisateur',
            field=models.CharField(choices=[('etudiant_chercheur', 'Étudiant Chercheur'), ('professeur_chercheur', 'Professeur Chercheur'), ('academique', 'Académique'), ('professionnel', 'Professionnel'), ('porteur_projet', 'Porteur de projet'), ('autre', 'Autre')], max_length=50, verbose_name="Type d'utilisateur"),
        ),
        migrations.AlterField(
            model_name='rendezvous',
            name='utilisateur',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='comptes.utilisateur', verbose_name='Utilisateur'),
        ),
        migrations.AlterField(
            model_name='utilisateur',
            name='adresse',
            field=models.TextField(blank=True, null=True, verbose_name='Adresse'),
        ),
        migrations.AlterField(
            model_name='utilisateur',
            name='date_inscription',
            field=models.DateTimeField(auto_now_add=True, verbose_name="Date d'inscription"),
        ),
        migrations.AlterField(
            model_name='utilisateur',
            name='derniere_connexion',
            field=models.DateTimeField(blank=True, null=True, verbose_name='Dernière connexion'),
        ),
        migrations.AlterField(
            model_name='utilisateur',
            name='email',
            field=models.EmailField(help_text='Cette adresse email sera utilisée pour vous connecter', max_length=254, unique=True, verbose_name='Email'),
        ),
        migrations.AlterField(
            model_name='utilisateur',
            name='est_actif',
            field=models.BooleanField(default=True, verbose_name='Compte actif'),
        ),
        migrations.AlterField(
            model_name='utilisateur',
            name='est_admin',
            field=models.BooleanField(default=False, verbose_name='Administrateur'),
        ),
        migrations.AlterField(
            model_name='utilisateur',
            name='est_bibliothecaire',
            field=models.BooleanField(default=False, verbose_name='Bibliothécaire'),
        ),
        migrations.AlterField(
            model_name='utilisateur',
            name='est_personnel',
            field=models.BooleanField(default=False, verbose_name='Personnel'),
        ),
        migrations.AlterField(
            model_name='utilisateur',
            name='favoris',
            field=models.ManyToManyField(blank=True, related_name='favoris_utilisateurs', to='bibliotheque.livre', verbose_name='Livres favoris'),
        ),
        migrations.AlterField(
            model_name='utilisateur',
            name='institution',
            field=models.CharField(blank=True, help_text="L'établissement auquel vous êtes rattaché", max_length=100, null=True, verbose_name='Institution'),
        ),
        migrations.AlterField(
            model_name='utilisateur',
            name='mot_de_passe',
            field=models.CharField(max_length=128, verbose_name='Mot de passe'),
        ),
        migrations.AlterField(
            model_name='utilisateur',
            name='nom',
            field=models.CharField(max_length=100, verbose_name='Nom'),
        ),
        migrations.AlterField(
            model_name='utilisateur',
            name='photo',
            field=models.ImageField(blank=True, help_text='Une photo de profil (optionnelle)', null=True, upload_to='photos_usagers/', verbose_name='Photo de profil'),
        ),
        migrations.AlterField(
            model_name='utilisateur',
            name='prenom',
            field=models.CharField(max_length=100, verbose_name='Prénom'),
        ),
        migrations.AlterField(
            model_name='utilisateur',
            name='profession',
            field=models.CharField(blank=True, help_text='Votre profession actuelle', max_length=100, null=True, verbose_name='Profession'),
        ),
        migrations.AlterField(
            model_name='utilisateur',
            name='secteur_activite',
            field=models.CharField(blank=True, help_text="Votre domaine d'activité", max_length=100, null=True, verbose_name="Secteur d'activité"),
        ),
        migrations.AlterField(
            model_name='utilisateur',
            name='telephone',
            field=models.CharField(blank=True, max_length=20, null=True, verbose_name='Téléphone'),
        ),
        migrations.AlterField(
            model_name='utilisateur',
            name='type_utilisateur',
            field=models.CharField(choices=[('etudiant', 'Étudiant'), ('professionnel', 'Professionnel'), ('membre_entreprise', "Membre d'entreprise")], help_text='Sélectionnez le type qui correspond le mieux à votre profil', max_length=20, verbose_name="Type d'utilisateur"),
        ),
    ]
