# Generated by Django 5.2.4 on 2025-08-12 08:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('bibliotheque', '0001_initial'),
        ('comptes', '0002_remove_profilbibliotheque_date_inscription_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='profilbibliotheque',
            name='favoris',
            field=models.ManyToManyField(blank=True, related_name='favoris_utilisateurs', to='bibliotheque.livre'),
        ),
    ]
