# Generated by Django 5.2.4 on 2025-08-13 14:08

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('comptes', '0003_profilbibliotheque_favoris'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AlterField(
            model_name='profilbibliotheque',
            name='utilisateur',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='comptes.usager'),
        ),
        migrations.CreateModel(
            name='RendezVous',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nom', models.CharField(max_length=100)),
                ('prenom', models.CharField(max_length=100)),
                ('telephone', models.CharField(max_length=20)),
                ('email', models.EmailField(max_length=254)),
                ('type_utilisateur', models.CharField(choices=[('etudiant_chercheur', 'Étudiant Chercheur'), ('professeur_chercheur', 'Professeur Chercheur'), ('academique', 'Académique'), ('professionnel', 'Professionnel'), ('porteur_projet', 'Porteur de projet'), ('autre', 'Autre')], max_length=50)),
                ('categorie_ouvrage', models.CharField(max_length=200)),
                ('titre_ouvrage', models.CharField(max_length=200)),
                ('auteur_ouvrage', models.CharField(blank=True, max_length=200, null=True)),
                ('numero_inventaire', models.CharField(blank=True, max_length=100, null=True)),
                ('ancien_code', models.CharField(blank=True, max_length=100, null=True)),
                ('raison', models.TextField()),
                ('date_souhaitee', models.DateField()),
                ('message', models.TextField(blank=True, null=True)),
                ('date_creation', models.DateTimeField(auto_now_add=True)),
                ('utilisateur', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
