# Generated by Django 5.1.5 on 2025-09-04 10:18

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('bibliotheque', '0001_initial'),
        ('comptes', '0003_alter_notification_options_alter_rendezvous_options_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='rendezvous',
            name='livre',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='rendezvous', to='bibliotheque.livre', verbose_name='Livre'),
        ),
    ]
