# Generated by Django 5.2.4 on 2025-09-13 18:44

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('comptes', '0004_alter_rendezvous_livre'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='rendezvous',
            name='livre',
        ),
        migrations.RemoveField(
            model_name='rendezvous',
            name='utilisateur',
        ),
        migrations.RemoveField(
            model_name='utilisateur',
            name='favoris',
        ),
        migrations.DeleteModel(
            name='Notification',
        ),
        migrations.DeleteModel(
            name='RendezVous',
        ),
        migrations.DeleteModel(
            name='Utilisateur',
        ),
    ]
